# Generated by Django 4.1.2 on 2022-10-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todolist",
            name="context",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name="todolist", name="title", field=models.CharField(max_length=80),
        ),
    ]
