# Generated by Django 4.1.2 on 2022-10-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0002_alter_todolist_context_alter_todolist_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="todolist",
            name="is_today",
            field=models.BooleanField(default=False),
        ),
    ]
